### ISSUE TITLE
Can we use JBuilder as renderer ?

### ISSUE THREAD

**Issue by nicolas-besnard** [owma/API#1]
https://github.com/rails/jbuilder

**Comment by baptiste-dulac** [comment]
Ouais pour moi pas de soucis, c'est du Json ?
Si c'est plus simple pour toi en plus c'est cool ?

**Comment by nicolas-besnard** [comment]
C'est un moteur de template. Actuellement, il n'y a pas de vu, le json est créé depuis le controller. C'est cool, ça marche bien, mais c'est plus "compliqué" (même si c'est pas vraiment compliqué).

Ça permet juste de ré-implémenter la partie View du MVC.

**Comment by baptiste-dulac** [comment]
Si ça permet d'être parfaitement en accord avec le pattern MVC, je pense que ça vaut le coup de l'implémenter !
