### ISSUE TITLE
Is the model Role useful ?

### ISSUE THREAD

**Issue by nicolas-besnard** [owma/API#4]

**Comment by baptiste-dulac** [comment]
Yep pour moi... C'est quoi qui te parait pas clair ?

**Comment by nicolas-besnard** [comment]
Oui oui, c'est utile, mais est-ce qu'un model en BDD est utile ? Au final, si on avait des constantes (ou un enum) dans le model User, ça reviendrait au même.

**Comment by baptiste-dulac** [comment]
Ok ok... Ben en fait je pense que c'est utile pour pouvoir gérer directement les role en fonction de l'event comme on en avait parlé. Par contre les capabilities seront des enums directement gérer dans le code ?
